create table if not exists public.knowledge_base (
  id bigint generated always as identity primary key,
  category text not null,
  content text not null,
  created_at timestamptz default now()
);

create index if not exists knowledge_base_fts
  on public.knowledge_base
  using gin(to_tsvector('portuguese', content));

alter table public.knowledge_base enable row level security;

create policy "Leitura pública" on public.knowledge_base
  for select using (true);

truncate table public.knowledge_base restart identity;

insert into public.knowledge_base (category, content) values
('transferencia', 'DOCUMENTOS OBRIGATÓRIOS PARA TRANSFERÊNCIA DE VEÍCULO (lista completa): 1. CRV assinado pelo vendedor com firma reconhecida em cartório, OU ATPV-e (documento digital — não precisa de firma reconhecida). 2. RG e CPF do comprador e do vendedor. 3. CNH do comprador (pode substituir RG). 4. Comprovante de residência atualizado (últimos 90 dias) do comprador. 5. Laudo CSV (Vistoria de Identificação Veicular) — OBRIGATÓRIO pelo DETRAN-SP para todos os veículos usados. O prazo para transferir após a compra é de 30 dias. Atraso gera multa e pode bloquear o licenciamento.'),
('transferencia', 'LAUDO CSV vs LAUDO CAUTELAR — diferença fundamental: • Laudo CSV (Certificado de Segurança Veicular / ECV): é OBRIGATÓRIO por lei para transferência. Verifica chassi, motor e identificação do veículo. Emitido por ECVs credenciadas pelo DETRAN. Sem ele, o DETRAN não processa a transferência. • Laudo Cautelar (Perícia Veicular): é OPCIONAL, feito por peritos particulares. Verifica histórico de colisões, leilão, recall. Serve para o comprador ter mais segurança na compra, mas NÃO é aceito pelo DETRAN para transferência. Nunca confundir: quem exige CSV é o DETRAN. Cautelar é escolha do comprador.'),
('transferencia', 'TRANSFERÊNCIA COM FINANCIAMENTO ATIVO: Se o veículo ainda tem financiamento (gravame no banco), é necessário: 1. Carta de anuência ou autorização do banco credor para transferência, OU 2. Carta de quitação do financiamento. O banco precisa liberar o gravame antes do DETRAN processar a transferência. Esse processo pode levar de 5 a 15 dias úteis dependendo da instituição financeira. O Despachante Paixão auxilia na comunicação com o banco e acompanha o processo.'),
('transferencia', 'PRAZO E MULTA POR ATRASO NA TRANSFERÊNCIA: O comprador tem 30 dias corridos após a assinatura do CRV para registrar a transferência no DETRAN. Após esse prazo: • Multa administrativa por atraso na transferência. • Multas geradas pelo vendedor após a venda continuam no nome do vendedor, mas podem gerar bloqueio para o comprador se o veículo não for transferido. • O vendedor pode registrar "comunicação de venda" no site do DETRAN-SP para se proteger de multas geradas após a venda. Recomendamos sempre transferir imediatamente após a compra para evitar complicações.'),
('transferencia', 'TAXA DE TRANSFERÊNCIA NO DETRAN-SP (TFDTE): O DETRAN-SP cobra a Taxa de Fiscalização e Serviços de Transferência de Propriedade (TFDTE). O valor exato varia conforme o tipo e categoria do veículo (automóvel, moto, caminhão, etc.) e é reajustado anualmente. Para consultar o valor atualizado e emitir a guia, fale pelo WhatsApp (11) 95328-4566.'),
('transferencia', 'COMUNICAÇÃO DE VENDA E CANCELAMENTO (2026): O vendedor deve registrar a Comunicação de Venda no portal do Detran-SP. Novidade 2026: O cancelamento da intenção ou da comunicação de venda agora é 100% digital e DISPENSA LAUDO DE VISTORIA, sendo um processo meramente administrativo via portal ou app Poupatempo.'),
('transferencia', 'TRANSFERÊNCIA INTERESTADUAL: Exige quitação total de débitos em SP antes da saída. O processo envolve o Detran de destino. Obrigatório Laudo CSV.'),
('transferencia', 'TRANSFERÊNCIA ENTRE ESTADOS: Se o comprador mora em outro estado, o veículo precisará ser transferido primeiro para o estado do novo proprietário. O processo envolve o DETRAN do estado de destino. Em SP, é necessário quitar todos os débitos (IPVA, multas, licenciamento) antes da transferência interestadual. O prazo pode ser maior. Consulte-nos pelo WhatsApp para orientação específica.'),
('licenciamento', 'CALENDÁRIO DE LICENCIAMENTO SP 2026 — Automóveis, Motos, Ônibus e Reboques (por final de placa): • Final 1 e 2: julho/2026 • Final 3 e 4: agosto/2026 • Final 5 e 6: setembro/2026 • Final 7 e 8: outubro/2026 • Final 9: novembro/2026 • Final 0: dezembro/2026. Veículos com IPVA pago à vista têm o prazo do mês correspondente ao final da placa. Pagamento parcelado: considerar data da última parcela. Vencimento no último dia útil do mês.'),
('licenciamento', 'CALENDÁRIO DE LICENCIAMENTO SP 2026 — Caminhões e Tratores (por final de placa): • Final 1 e 2: setembro/2026 • Final 3, 4 e 5: outubro/2026 • Final 6, 7 e 8: novembro/2026 • Final 9 e 0: dezembro/2026. Vencimento no último dia útil do mês.'),
('licenciamento', 'O QUE É NECESSÁRIO PARA LICENCIAR (CRLV anual): 1. IPVA do ano quitado (à vista ou última parcela paga). 2. Seguro DPVAT pago (quando aplicável). 3. Multas de trânsito quitadas ou com recurso em andamento válido. 4. Taxa de Licenciamento Estadual (TFDLE) recolhida. 5. Não ter restrições administrativas. Com tudo quitado, o CRLV fica disponível automaticamente no sistema.'),
('licenciamento', 'CRLV DIGITAL — como obter gratuitamente: O CRLV digital tem validade legal idêntica ao físico. 1. Aplicativo "Carteira Digital de Trânsito" (CDT). 2. Portal do SENATRAN / gov.br. 3. O Despachante Paixão pode auxiliar a baixar, imprimir ou plastificar se precisar.'),
('licenciamento', 'CONSEQUÊNCIAS DE NÃO LICENCIAR NO PRAZO: Circular com licenciamento vencido é infração GRAVÍSSIMA: • 7 pontos na CNH. • Multa. • Retenção do veículo na fiscalização. • Impedimento de transferência e outros serviços no DETRAN. Regularize antes do vencimento para evitar esses problemas.'),
('licenciamento', 'EMPLACAMENTO DE VEÍCULO NOVO (0km): Documentos: Nota Fiscal, CPF/RG do comprador, Comprovante de endereço. Escolha da placa (modelo Mercosul). O Despachante Paixão realiza o processo completo em 1 a 3 dias úteis.'),
('licenciamento', 'LICENCIAMENTO COM DÉBITOS ANTIGOS — como regularizar: Veículos com débitos de anos anteriores podem ser regularizados via pagamento à vista, parcelamento pelo DETRAN-SP ou contestação de multas. O Despachante Paixão consulta a situação completa via WhatsApp (11) 95328-4566.'),
('multas', 'COMO CONSULTAR MULTAS E DÉBITOS DO VEÍCULO: A consulta é feita pelo número da placa ou RENAVAM. O Despachante Paixão faz essa consulta gratuitamente via WhatsApp (11) 95328-4566 enviando placa ou RENAVAM.'),
('multas', 'COMO RECORRER DE MULTA DE TRÂNSITO: 1. Defesa Prévia (até 30 dias da autuação). 2. Recurso JARI (1ª instância). 3. Recurso CETRAN (2ª instância). Durante o recurso a multa fica suspensa e não gera pontos. O Despachante Paixão auxilia na elaboração e protocolo.'),
('multas', 'SUSPENSÃO DA CNH POR PONTOS: • 20 pontos (infratores primários). • 30 pontos (sem infração grave/gravíssima em 12 meses). • 40 pontos (sem infrações em 12 meses). A suspensão pode ser de 6 meses a 1 ano.'),
('multas', 'NOTIFICAÇÃO DE MULTA — o que fazer: 1. Verifique os dados. 2. Indique o condutor real se não foi você. 3. Pague ou recorra. O Despachante Paixão orienta em todos esses casos.'),
('multas', 'BLOQUEIO DO VEÍCULO POR MULTAS OU DÉBITOS: Veículos com muitas multas ou débitos atrasados podem ter o licenciamento e transferência bloqueados. Para regularizar é necessário quitar ou parcelar os débitos.'),
('vistoria', 'LAUDO CSV (Vistoria de Identificação Veicular) — tudo sobre: • O que é: perícia oficial por ECVs credenciadas. • O que verifica: chassi, motor, identificação estrutural. • Quando é obrigatório: em toda transferência de veículo usado, mudança de município, alteração de características (cor, carroceria), regularização de veículo com restrição. • Validade: em geral 90 dias após a emissão, mas pode variar. Use logo após obter. • Onde fazer: em qualquer ECV credenciada pelo DETRAN. O Despachante Paixão indica e auxilia no agendamento.'),
('vistoria', 'VISTORIA OBRIGATÓRIA — quando é exigida: 1. Transferência de propriedade (veículo usado): sempre exige Laudo CSV. 2. Mudança de município de registro: exige vistoria. 3. Alteração de características: mudança de cor, tipo de carroceria, adaptações — exige vistoria. 4. Regularização de chassi ou motor: veículos com adulteração de identificação exigem perícia especial. 5. Veículos de leilão: sempre exige vistoria antes da transferência. 6. Segundo emplacamento: veículos importados ou reassentados.'),
('vistoria', 'VISTORIA (MUDANÇAS 2026): O pagamento da vistoria obrigatória (ECV) agora é feito via boleto do Detran-SP, não mais à empresa. DISPENSA DE LAUDO 2026: Não precisa mais de laudo para: 2ª via de CRV, Troca para Placa Mercosul (adequação) e Cancelamento de venda. O Laudo CSV continua OBRIGATÓRIO para: Transferência, Mudança de Cidade/Estado e Alteração de Característica.'),
('vistoria', 'PRAZO DA VISTORIA NO DETRAN-SP: Realizada em média em 3 a 10 dias úteis após agendamento. O laudo fica disponível no sistema do DETRAN. O Despachante Paixão acompanha o resultado.'),
('ipva', 'IPVA SP: Alíquota de 4% para carros/pick-ups; 2% para caminhões/ônibus; 1,5% para motos. Base de cálculo via tabela FIPE. Isenção para veículos com mais de 20 anos, táxis e PCD.'),
('ipva', 'IPVA ATRASADO — consequências: Gera juros, multa de mora, inscrição em dívida ativa e bloqueio do licenciamento/transferência. Regularize via site da SEFAZ-SP ou banco autorizado.'),
('regularizacao', 'REGULARIZAÇÃO DE VEÍCULO COM RESTRIÇÕES: Resolvendo roubo/furto (BO e perícia), financeira (gravame), administrativa (débitos) ou judicial (ordem do juiz). O Despachante Paixão analisa seu caso.'),
('regularizacao', '2ª VIA CRV E PLACA MERCOSUL (REGRAS 2026): A 2ª via do CRV por perda ou dano e a conversão para Placa Mercosul (quando não há troca de dono) NÃO PRECISAM MAIS DE LAUDO DE VISTORIA. O processo é administrativo e digital via Portal Detran-SP ou Poupatempo.'),
('regularizacao', 'SEGUNDA VIA DO CRV / ATPV-e (NOVO 2026): Para documentos perdidos ou danificados, a partir de Jan/2026, NÃO É NECESSÁRIO LAUDO DE VISTORIA. O processo é digital, feito pelo Portal do Detran-SP ou aplicativo Poupatempo. Se o CRV físico foi perdido antes de 2021 (documento verde), o atendimento presencial em um posto do Poupatempo ou Detran ainda se faz necessário para a atualização cadastral. Para o ATPV-e (digital), basta baixar o arquivo atualizado gratuitamente pelo aplicativo Carteira Digital de Trânsito (CDT) ou pelo portal Poupatempo.'),
('regularizacao', 'TROCA DE PLACA PARA MODELO MERCOSUL (NOVO 2026): A partir de Jan/2026, para a troca de placa para o padrão Mercosul (por adequação, furto, extravio ou dano), NÃO É NECESSÁRIO LAUDO DE VISTORIA. O pagamento da Autorização de Estampagem (AEPIV) é feito diretamente ao Detran-SP (taxa fixa de R$30-R$37), e a liberação é digital e instantânea. O proprietário vai à estampadora apenas para pagar a fabricação física da placa. O BO é recomendado em caso de furto/perda.'),
('regularizacao', 'LACRE DE PLACA — quando é necessário: Quando a placa está danificada, ilegível ou foi furtada/roubada. Exige CRV/CRLV, RG/CPF do dono e BO em caso de furto.'),
('cnh', 'RENOVAÇÃO CNH E AUTOESCOLA (REGRAS 2026): 1. Bons motoristas (sem multas em 12 meses) têm renovação automática e gratuita pelo app CDT. 2. Primeira Habilitação: Fim da obrigatoriedade de autoescola; aulas teóricas gratuitas/online e aulas práticas reduzidas para 2h (pode usar instrutor autônomo ou carro próprio).'),
('cnh', 'PRIMEIRA HABILITAÇÃO (CNH) - MUDANÇAS 2026: A partir de Jan/2026, o monopólio das autoescolas para a Primeira Habilitação foi encerrado. Aulas teóricas podem ser online e gratuitas (via app CNH do Brasil). A exigência de aulas práticas obrigatórias caiu de 20h para 2h, podendo ser feitas com instrutor autônomo ou carro próprio/familiar. Exames médico, psicológico, teórico e prático no Detran permanecem. A emissão digital é gratuita.'),
('cnh', 'ADIÇÃO DE CATEGORIA NA CNH: Exige exames, curso teórico/prático em autoescola credenciada e exame no DETRAN. O Despachante Paixão orienta a documentação necessária.'),
('cnh', 'SEGUNDA VIA DA CNH — como solicitar: Em caso de perda, furto ou dano: 1. Registrar Boletim de Ocorrência (para furto/roubo). 2. Solicitar segunda via pelo site do DETRAN-SP ou presencialmente. 3. Pagar a taxa de emissão. 4. Fazer foto e coleta de biometria (se necessário). Prazo médio: 5 a 15 dias úteis para recebimento. O Despachante Paixão orienta e pode auxiliar no processo.'),
('atendimento', 'SERVIÇOS COMPLETOS DO DESPACHANTE PAIXÃO (Guarulhos-SP): • Transferência de veículo (com ou sem financiamento) • Licenciamento anual (CRLV) • Emplacamento de veículo novo ou transferência de placa • Vistoria / Laudo CSV — agendamento e acompanhamento • Recurso de multas de trânsito • Consulta de débitos e restrições • Segunda via de CRV, CRLV e CNH • Renovação e adição de categoria na CNH • Regularização de veículos com débitos antigos • Lacre de placa • Comunicação de venda • Transferência interestadual. Atendemos presencialmente em Guarulhos-SP e online pelo WhatsApp.'),
('atendimento', 'HORÁRIO DE ATENDIMENTO DO DESPACHANTE PAIXÃO: Segunda a sexta das 07h às 22h, sábado das 08h às 18h e domingo das 08h às 14h. Atendimento presencial: Guarulhos-SP. WhatsApp: (11) 95328-4566. Para dúvidas rápidas, respondemos aqui pelo chat. Para solicitar um serviço ou orçamento, fale pelo WhatsApp.'),
('atendimento', 'PRAZO MÉDIO DOS SERVIÇOS — Despachante Paixão: • Transferência simples: 3 a 7 dias úteis (após entrega de todos os documentos). • Transferência com financiamento: 7 a 15 dias úteis (depende do banco). • Emplacamento de veículo novo: 1 a 3 dias úteis. • Licenciamento (CRLV): 1 a 2 dias úteis após quitação dos débitos. • Vistoria / Laudo CSV: 3 a 10 dias úteis (conforme demanda do DETRAN). • Renovação de CNH: 10 a 20 dias úteis. • Recurso de multa: elaboração em 1 a 3 dias úteis; julgamento pela JARI pode levar 30 a 90 dias.'),
('atendimento', 'FORMAS DE PAGAMENTO — Despachante Paixão: • Pix (preferencial — mais ágil) • Dinheiro • Cartão de débito e crédito. ATENÇÃO: As taxas oficiais do DETRAN-SP (IPVA, licenciamento, transferência, multas) são pagas separadamente via guia oficial, em banco autorizado ou app. O Despachante Paixão cobra apenas pelos serviços de despachante. Consulte o valor do serviço pelo WhatsApp (11) 95328-4566.'),
('atendimento', 'POR QUE USAR UM DESPACHANTE: • Economia de tempo: evita filas e idas ao DETRAN. • Segurança: documentação conferida por profissional experiente. • Agilidade: conhecemos todos os requisitos e processos do DETRAN-SP. • Acompanhamento: monitoramos o processo e avisamos sobre cada etapa. • Prevenção de erros: documentação incorreta pode atrasar ou cancelar o processo. O Despachante Paixão tem anos de experiência em Guarulhos e região.');